import Link from 'next/link';
import { Site } from '../../site';
export const dynamic='force-static';
export default function Page(){return <Site><main><header className="topic-hero"><div className="container"><Link className="back-link" href="/flyer/">← チラシへ戻る</Link><p className="eyebrow" style={{color:'#0017c1'}}>FLYER / SECTION 02</p><h1>GIADの技術とモデル内部</h1><p className="lead">GIADは、各知識の理解確率を更新し、知識グラフへ証拠を伝え、全体の不確かさを最も減らす次問を選ぶ、説明可能な適応型診断モデルです。</p></div></header><div className="container section topic-layout"><aside className="topic-nav"><strong>このページの内容</strong><a href="#overview">全体像</a><a href="#response">回答モデル</a><a href="#bayes">ベイズ更新</a><a href="#graph">グラフ伝播</a><a href="#selection">次問選択</a><a href="#stop">停止条件</a><a href="#llm">生成AIとの境界</a></aside><article className="topic-body">
 <section id="overview"><p className="eyebrow" style={{color:'#0017c1'}}>MODEL OVERVIEW</p><h2>GIADが持つ3種類のデータ</h2><div className="model-grid"><article><b>知識ノード</b><p>各知識に理解確率 p を持たせます。初期値は0.5で、「分かる・分からないが同程度に不確か」な状態です。</p></article><article><b>関係エッジ</b><p>同義、類似、前提関係を区別します。類似度や前提方向を、回答後の伝播に使います。</p></article><article><b>問題項目</b><p>対象ノード、識別力、難易度、推測正答率、うっかり誤答率、所要時間、認知負荷を持ちます。</p></article></div></section>
 <section id="response"><p className="eyebrow" style={{color:'#0017c1'}}>RESPONSE MODEL</p><h2>理解度から正答確率を計算する</h2><p>問題には識別力 a、難易度 b、推測正答率 g、うっかり誤答率 s を設定します。理解確率 p をロジットへ変換し、次の4パラメータ型の式で正答確率を求めます。</p><div className="formula">P(正答｜p) = g + (1 − g − s) ÷ (1 + exp{`{`}−a(logit(p) − b){`}`})</div><p>合成実験の項目バンクでは、各ノードに難易度の異なる3問を生成し、識別力は1.2または1.4、推測正答率は0.25、うっかり誤答率は0.10を既定値としています。</p></section>
 <section id="bayes"><p className="eyebrow" style={{color:'#0017c1'}}>BAYES UPDATE</p><h2>一つの回答で対象知識の確率を更新する</h2><p>回答前の理解確率を事前確率、問題モデルから得た正答・誤答の起こりやすさを尤度として、ベイズ則で事後確率を計算します。正答なら理解側へ、誤答なら未理解側へ動きますが、問題の難易度や推測正答も考慮するため、正誤だけで0または1に決めません。</p><div className="model-flow"><span>事前確率<br/><b>p = 0.5</b></span><i>＋ 回答の尤度</i><span>ベイズ更新</span><i>→</i><span>事後確率<br/><b>0.005〜0.995</b></span></div></section>
 <section id="graph"><p className="eyebrow" style={{color:'#0017c1'}}>GRAPH PROPAGATION</p><h2>直接聞いていない知識へ、弱い証拠を伝える</h2><ul><li><strong>equivalent：</strong>同値グループの理解確率を平均し、同じ概念の表現違いをそろえる</li><li><strong>similar：</strong>類似度0.12以上のノード同士を、既定強度0.12×類似度だけ近づける</li><li><strong>prerequisite：</strong>応用側が前提側より高い不自然な差を検出し、既定強度0.25で前提を上げ、応用を弱く下げる</li></ul><p>伝播は2回反復します。これはニューラルネットワークが学習した不透明な重みではなく、コード上で確認・調整できる明示的な規則です。</p></section>
 <section id="selection"><p className="eyebrow" style={{color:'#0017c1'}}>QUESTION SELECTION</p><h2>期待情報利得から「次の一問」を選ぶ</h2><p>各候補問題について、正答した場合と誤答した場合のモデルを仮に作り、回答後の総エントロピーを予測します。回答前との差が期待情報利得です。さらに未出題範囲の網羅性を加点し、既出知識との重複と回答負担を減点します。</p><div className="formula">score = 情報利得 + 0.08×coverage − 0.10×redundancy − 0.03×burden</div><p>したがってGIADは、単に最も難しい問題を選ぶのではなく、「全知識について残っている不確かさを、次の回答でどれだけ減らせるか」を基準にします。</p></section>
 <section id="stop"><p className="eyebrow" style={{color:'#0017c1'}}>STOPPING RULE</p><h2>必要な確信が得られたら終了する</h2><p>対象ノードすべてで分散 p(1−p) が0.20以下になった場合、または弱点境界0.5から十分離れて90%相当の確信が得られた場合に停止できます。予備実験では方式を公平に比べるため、最大8問の共通予算も設定しています。</p></section>
 <section id="llm"><p className="eyebrow" style={{color:'#0017c1'}}>ROLE OF LLM</p><h2>生成AIは問題の草案、GIADは数値推定</h2><p>研究評価用のGIADコアはLLMから独立しており、理解確率の更新と次問選択は明示的な数式で行います。Ollama／Gemmaは問題文の草案や自由記述の構造化に利用しますが、合成実験の理解度推定をLLMへ任せてはいません。</p><div className="fact"><strong>実装上の区別</strong><br/>現在の対話型プロトタイプには、Gemmaが回答から理解度・確かさ・根拠を直接出す実装もあります。予備実験でIndependent CATと比較したGIADは、ベイズ更新・情報利得・グラフ伝播を使う測定可能な研究コアです。</div></section>
 </article></div><section className="next-page"><Link href="/topics/experiment/"><span>次のチラシ項目</span><strong>予備実験のデータ</strong><b>→</b></Link></section></main></Site>}
